name: Build Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install Gradle and Build
      run: |
        cd android
        # Устанавливаем Gradle Wrapper (создаст и .jar, и gradlew)
        gradle wrapper
        # Даем права новому файлу
        chmod +x gradlew
        # Запускаем сборку
        ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: puma-taxi-apk
        path: "android/app/build/outputs/apk/release/*.apk"
